#!/usr/bin/env bash


# only install glide if it is not installed
type glide >/dev/null 2>&1 || (echo "installing Glide" && curl https://glide.sh/get | sh )


pushd src/datadog-firehose-nozzle/github.com/DataDog/datadog-firehose-nozzle
  glide install
popd
