---
name: datadog

releases:
  - name: datadog-firehose-nozzle
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/datadog-firehose-nozzle-release
    version: latest

update:
  canaries: 1
  canary_watch_time: 30000-100000
  update_watch_time: 30000-100000
  max_in_flight: 1
  max_errors: 1

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: nozzle
  azs:
  - z1
  instances: 1
  persistent_disk_type: 5GB
  vm_type: default
  stemcell: default
  networks:
  - name: private
  jobs:
  - name: datadog-firehose-nozzle
    release: datadog-firehose-nozzle
    properties:
      loggregator:
        traffic_controller_url: "((tc_url))"
      datadog:
        api_url: "((datadog_api))"
        api_key: "((datadog_key))"
        flush_duration_seconds: 15
        metric_prefix: datadog.nozzle.
      uaa:
        url: "((uaa_url))"
        client: "((uaa_client))"
        client_secret: "((uaa_secret))"
      nozzle:
        insecure_ssl_skip_verify: false
        subscription_id: datadog-nozzle
        deployment: datadog
